"""empty message

Revision ID: 8732eba9fa97
Revises: 0190b759b89e
Create Date: 2023-04-14 15:45:49.992108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8732eba9fa97'
down_revision = '0190b759b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('items_ibfk_1', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
